export const ADD_MESSAGE = "@message-list/add message"
export const DELETE_MESSAGE = "@message-list/delete message"
export const EDIT_MESSAGE = "@message-list/edit message"
export const ADD_MESSAGE_ROOM = "@message-list/add new room"
export const DELETE_MESSAGE_ROOM = "@message-list/delete room"
export const GET_MESSAGES_START = "@message-list/get messages fb start"
export const GET_MESSAGES_SUCCESS = "@message-list/get messages fb success"
export const GET_MESSAGES_ERROR = "@message-list/get messages fb error"
export const RECEIVE_MESSAGE = "@message-list/receive message from fb db"
export const RECEIVE_MESSAGE_UPDATE =
  "@message-list/receive message update from fb db"
